config/routes.rb
Rails.application.routes.draw do
  get 'home/index'
  root 'home#index'
  get 'home/stage'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def stage
    @stage = params[:stage]
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<div class="container text-center mt-3">
        <div class="mt-4">
            <%= image_tag 'gorilla.png', alt: 'ゴリラ画像', class: 'img-fluid' %>
        </div>
        <br>
        <h2>どのステージで話す？</h2>
        <div class="container">
          <div class="btn-group-vertical w-100 mx-auto">
              <%= link_to 'マウティングゴリラ編', home_stage_path(stage: 1), class: 'btn btn-secondary', role: 'button' %>
              <%= link_to 'お嬢様編',home_stage_path(stage: 2), class: 'btn btn-secondary', role: 'button' %>
              <%= link_to '同僚編', home_stage_path(stage: 3), class: 'btn btn-secondary', role: 'button' %>
              <%= link_to '上司編', home_stage_path(stage: 4), class: 'btn btn-secondary', role: 'button' %>
              <%= link_to '担当者編', home_stage_path(stage: 5), class: 'btn btn-secondary', role: 'button' %>
              
              <%= link_to 'https://twitter.com/intent/tweet?' + { text: '難易度の高いキャラクターたちとの会話でコミュ力アップを!! #うんざりピーポーマスター', url: 'https://unzari.onrender.com/' }.to_query, target: '_blank', class: 'twitter-share-button' do %>
                  <i class="fa-brands fa-x-twitter black-text"></i><span class="black-text"> で共有する</span>
              <% end %>
          </div>
        </div>
    </div>
    <br>

app/views/home/stage.html.erb
<div class="container text-center mt-3">
  <% case @stage %>
  <% when "1" %>
    <div class="mt-4">
        <%= image_tag 'gorilla2.jpg', alt: 'ゴリラ画像', class: 'img-fluid' %>
        <P>あなた「おはようございます」</p>
        <p>ゴリラ「あ？」</p>
        <p>のように会話スペースを作成する</p>
    </div>
  <% when "2" %>
    <%= image_tag 'ojousama.jpg', alt: 'お嬢様画像', class: 'img-fluid' %>
    <p>お嬢様 「うだうだ ぐちぐち ぶつぶつ...」</p>
    <p>あなた 「😫😵😢😭」</p>
  <% when "3" %>
  <%= image_tag 'douryou.jpg', alt: '同僚画像', class: 'img-fluid' %>
    <p>あなた「明日はこの仕事を担当してくれるかな？」</p>
    <p>同僚 「無理！無理！俺には無理！あっ。○○さんから電話だ。じゃあ」</P>
    <p>あなた 「.....」</P>
  <% when "4" %>
  <%= image_tag 'joushi.jpg', alt: '上司画像', class: 'img-fluid' %>
    <p>上司 「その書類作りなおそうか？」</p>
    <p>あなた 「なぜですか？どこか問題ありました？」
    <p>上司 「表現のしかたが良くないと思うんだよね」</P>
    <p>あなた 「......」</p>
  <% when "5" %>
    <%= image_tag 'tantousha.jpg', alt: '担当者画像', class: 'img-fluid' %>
    <P>担当者「今度ご飯行こうよ。いつ休み？」</P>
    <P>あなた「......」</p>
  <% else %>
    <p>ステージを選んでください。</p>
  <% end %>
</div>

app/views/layouts/_navbar.html.erb
<header class="mb-4">
  <nav class="navbar navbar-expand-sm navbar-dark bg-dark">
    <a class="navbar-brand rock-text" href="/">うんざりピーポーマスター</a>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>うんざりピーポーマスター</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <!-- FBや他のソーシャルメディアで共有された時のリンクぷれびゅーに表示される情報の定義 -->
    <meta property="og:title" content="うんざりピーポーマスター" />
    <meta property="og:type" content="website" />
    <meta property="og:url" contente="https://unzari.onrender.com/" />
    <meta property="og:image" content="https://unzari.onrender.com/gorilla240.jpg" />
    <meta property="og:description" content="難易度の高いキャラクターたちとの会話でコミュ力アップを!!" />
    <meta property="og:site_name" content="うんざりピーポーマスター" />
    <meta property="og:type" content:"website" />

    <!-- X（旧Twitter） Card tags -->
    <meta name="twitter:card" content="summary" />
    <meta name="twitter:site" content="@kawara20230719" />
    <meta property="og:url" content="https://unzari.onrender.com/" />
    <meta property="og:site_name" content="うんざりピーポーマスター" />
    <meta property="og:image" content="https://unzari.onrender.com/gorilla240.jpg" />

    <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", type: "module" %>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.2/css/all.min.css">
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <%= yield %>
  </body>
</html>